### ISSUE TITLE
Ast -> AST + formatting rules and back converter.

### ISSUE THREAD

**Issue by matu3ba** [speed2exe/tree-fmt#1]
Zig is missing an AST representation to do AST-based diffing + patching.

As of now, `zig fmt` rules traverse the AST recursively and have complex rules, which makes usage of the AST cumbersome.

This is also a prequisite for an optimal solution to https://github.com/ziglang/zig/issues/14314#issuecomment-1386755813 (detect duplicate code fragments).

Feel free to close, if you are not interested.

**Comment by speed2exe** [comment]
Thanks for letting me know, however I'm afraid I can't commit much at this time. I'll close the issue for now.
